import { createFileRoute } from "@tanstack/react-router";
import { PageHero, Section } from "@/components/Section";
import { SITE } from "@/lib/site";
import { pageMeta } from "@/lib/seo";

export const Route = createFileRoute("/terms")({
  head: () =>
    pageMeta(
      "Terms & Conditions",
      "The terms that apply to enquiries, orders, delivery, installation and design services provided by Reno Luxe & Interior.",
    ),
  component: Terms,
});

const SECTIONS = [
  [
    "Enquiries and quotations",
    "Product listings and packages on this website are invitations to enquire, not binding offers. Pricing, availability, delivery cost and timelines are confirmed in writing during the enquiry and are valid for the period stated in that quotation.",
  ],
  [
    "Orders and payment",
    "An order is confirmed once you accept the quotation and the agreed payment terms are met. Payment terms for projects are set out in the project agreement.",
  ],
  [
    "Delivery",
    "Products are delivered worldwide. Delivery dates are estimates and may be affected by customs, carriers and availability. Any duties or import charges in the destination country are the customer's responsibility unless agreed otherwise in writing.",
  ],
  [
    "Installation and project work",
    "Installation, renovation and on-site execution are available within Nigeria. Site access, power and any building approvals are the client's responsibility.",
  ],
  [
    "Images and concepts",
    "Portfolio items marked as concepts are design directions, not completed client projects. Images generated by the Visualize Your Space tool are conceptual and do not represent a guaranteed final result.",
  ],
  [
    "Returns and variations",
    "Because many pieces are sourced or made to order, returns are handled case by case. Report damage in transit within 48 hours of delivery with photographs so we can resolve it with the carrier.",
  ],
  [
    "Liability",
    "We are not liable for indirect or consequential losses. Nothing in these terms limits liability where it cannot be limited by law.",
  ],
];

function Terms() {
  return (
    <>
      <PageHero
        overline="Legal"
        title="Terms & conditions"
        lead="The terms that apply when you enquire, order or work with us."
      />
      <Section>
        <div className="grid max-w-3xl gap-8">
          {SECTIONS.map(([title, body]) => (
            <article key={title}>
              <h2 className="font-display text-2xl">{title}</h2>
              <p className="mt-2.5 text-sm leading-relaxed text-muted-foreground">{body}</p>
            </article>
          ))}
          <p className="text-sm leading-relaxed text-muted-foreground">
            Questions? Contact us at{" "}
            <a href={`mailto:${SITE.email}`} className="text-primary">
              {SITE.email}
            </a>{" "}
            or on WhatsApp {SITE.phone}.
          </p>
        </div>
      </Section>
    </>
  );
}
