/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ConsultationRouteImport } from './routes/consultation'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DeliveryRouteImport } from './routes/delivery'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PlansRouteImport } from './routes/plans'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as VijuRouteImport } from './routes/viju'
import { Route as VisualizeRouteImport } from './routes/visualize'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'
import { Route as AuthenticatedFavouritesRouteImport } from './routes/_authenticated/favourites'
import { Route as ApiGenerateImageRouteImport } from './routes/api/generate-image'
import { Route as PortfolioSlugRouteImport } from './routes/portfolio.$slug'
import { Route as ProductsSlugRouteImport } from './routes/products.$slug'
import { Route as ServicesSlugRouteImport } from './routes/services.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultationRoute = ConsultationRouteImport.update({
  id: '/consultation',
  path: '/consultation',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DeliveryRoute = DeliveryRouteImport.update({
  id: '/delivery',
  path: '/delivery',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PlansRoute = PlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const VijuRoute = VijuRouteImport.update({
  id: '/viju',
  path: '/viju',
  getParentRoute: () => rootRouteImport,
} as any)
const VisualizeRoute = VisualizeRouteImport.update({
  id: '/visualize',
  path: '/visualize',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFavouritesRoute = AuthenticatedFavouritesRouteImport.update({
  id: '/favourites',
  path: '/favourites',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiGenerateImageRoute = ApiGenerateImageRouteImport.update({
  id: '/api/generate-image',
  path: '/api/generate-image',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioSlugRoute = PortfolioSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => PortfolioRoute,
} as any)
const ProductsSlugRoute = ProductsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ProductsRoute,
} as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ServicesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/consultation': typeof ConsultationRoute
  '/contact': typeof ContactRoute
  '/delivery': typeof DeliveryRoute
  '/faq': typeof FaqRoute
  '/login': typeof LoginRoute
  '/plans': typeof PlansRoute
  '/portfolio': typeof PortfolioRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/products': typeof ProductsRouteWithChildren
  '/services': typeof ServicesRouteWithChildren
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/viju': typeof VijuRoute
  '/visualize': typeof VisualizeRoute
  '/account': typeof AuthenticatedAccountRoute
  '/favourites': typeof AuthenticatedFavouritesRoute
  '/api/generate-image': typeof ApiGenerateImageRoute
  '/portfolio/$slug': typeof PortfolioSlugRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/consultation': typeof ConsultationRoute
  '/contact': typeof ContactRoute
  '/delivery': typeof DeliveryRoute
  '/faq': typeof FaqRoute
  '/login': typeof LoginRoute
  '/plans': typeof PlansRoute
  '/portfolio': typeof PortfolioRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/products': typeof ProductsRouteWithChildren
  '/services': typeof ServicesRouteWithChildren
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/viju': typeof VijuRoute
  '/visualize': typeof VisualizeRoute
  '/account': typeof AuthenticatedAccountRoute
  '/favourites': typeof AuthenticatedFavouritesRoute
  '/api/generate-image': typeof ApiGenerateImageRoute
  '/portfolio/$slug': typeof PortfolioSlugRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/consultation': typeof ConsultationRoute
  '/contact': typeof ContactRoute
  '/delivery': typeof DeliveryRoute
  '/faq': typeof FaqRoute
  '/login': typeof LoginRoute
  '/plans': typeof PlansRoute
  '/portfolio': typeof PortfolioRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/products': typeof ProductsRouteWithChildren
  '/services': typeof ServicesRouteWithChildren
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/viju': typeof VijuRoute
  '/visualize': typeof VisualizeRoute
  '/_authenticated/account': typeof AuthenticatedAccountRoute
  '/_authenticated/favourites': typeof AuthenticatedFavouritesRoute
  '/api/generate-image': typeof ApiGenerateImageRoute
  '/portfolio/$slug': typeof PortfolioSlugRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/consultation'
    | '/contact'
    | '/delivery'
    | '/faq'
    | '/login'
    | '/plans'
    | '/portfolio'
    | '/privacy'
    | '/products'
    | '/services'
    | '/signup'
    | '/terms'
    | '/viju'
    | '/visualize'
    | '/account'
    | '/favourites'
    | '/api/generate-image'
    | '/portfolio/$slug'
    | '/products/$slug'
    | '/services/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/consultation'
    | '/contact'
    | '/delivery'
    | '/faq'
    | '/login'
    | '/plans'
    | '/portfolio'
    | '/privacy'
    | '/products'
    | '/services'
    | '/signup'
    | '/terms'
    | '/viju'
    | '/visualize'
    | '/account'
    | '/favourites'
    | '/api/generate-image'
    | '/portfolio/$slug'
    | '/products/$slug'
    | '/services/$slug'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/consultation'
    | '/contact'
    | '/delivery'
    | '/faq'
    | '/login'
    | '/plans'
    | '/portfolio'
    | '/privacy'
    | '/products'
    | '/services'
    | '/signup'
    | '/terms'
    | '/viju'
    | '/visualize'
    | '/_authenticated/account'
    | '/_authenticated/favourites'
    | '/api/generate-image'
    | '/portfolio/$slug'
    | '/products/$slug'
    | '/services/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  ConsultationRoute: typeof ConsultationRoute
  ContactRoute: typeof ContactRoute
  DeliveryRoute: typeof DeliveryRoute
  FaqRoute: typeof FaqRoute
  LoginRoute: typeof LoginRoute
  PlansRoute: typeof PlansRoute
  PortfolioRoute: typeof PortfolioRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  ProductsRoute: typeof ProductsRouteWithChildren
  ServicesRoute: typeof ServicesRouteWithChildren
  SignupRoute: typeof SignupRoute
  TermsRoute: typeof TermsRoute
  VijuRoute: typeof VijuRoute
  VisualizeRoute: typeof VisualizeRoute
  ApiGenerateImageRoute: typeof ApiGenerateImageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consultation': {
      id: '/consultation'
      path: '/consultation'
      fullPath: '/consultation'
      preLoaderRoute: typeof ConsultationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delivery': {
      id: '/delivery'
      path: '/delivery'
      fullPath: '/delivery'
      preLoaderRoute: typeof DeliveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plans': {
      id: '/plans'
      path: '/plans'
      fullPath: '/plans'
      preLoaderRoute: typeof PlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/viju': {
      id: '/viju'
      path: '/viju'
      fullPath: '/viju'
      preLoaderRoute: typeof VijuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/visualize': {
      id: '/visualize'
      path: '/visualize'
      fullPath: '/visualize'
      preLoaderRoute: typeof VisualizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/favourites': {
      id: '/_authenticated/favourites'
      path: '/favourites'
      fullPath: '/favourites'
      preLoaderRoute: typeof AuthenticatedFavouritesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/generate-image': {
      id: '/api/generate-image'
      path: '/api/generate-image'
      fullPath: '/api/generate-image'
      preLoaderRoute: typeof ApiGenerateImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio/$slug': {
      id: '/portfolio/$slug'
      path: '/$slug'
      fullPath: '/portfolio/$slug'
      preLoaderRoute: typeof PortfolioSlugRouteImport
      parentRoute: typeof PortfolioRoute
    }
    '/products/$slug': {
      id: '/products/$slug'
      path: '/$slug'
      fullPath: '/products/$slug'
      preLoaderRoute: typeof ProductsSlugRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/services/$slug': {
      id: '/services/$slug'
      path: '/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof ServicesRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRoute
  AuthenticatedFavouritesRoute: typeof AuthenticatedFavouritesRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccountRoute: AuthenticatedAccountRoute,
  AuthenticatedFavouritesRoute: AuthenticatedFavouritesRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface PortfolioRouteChildren {
  PortfolioSlugRoute: typeof PortfolioSlugRoute
}

const PortfolioRouteChildren: PortfolioRouteChildren = {
  PortfolioSlugRoute: PortfolioSlugRoute,
}

const PortfolioRouteWithChildren = PortfolioRoute._addFileChildren(
  PortfolioRouteChildren,
)

interface ProductsRouteChildren {
  ProductsSlugRoute: typeof ProductsSlugRoute
}

const ProductsRouteChildren: ProductsRouteChildren = {
  ProductsSlugRoute: ProductsSlugRoute,
}

const ProductsRouteWithChildren = ProductsRoute._addFileChildren(
  ProductsRouteChildren,
)

interface ServicesRouteChildren {
  ServicesSlugRoute: typeof ServicesSlugRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesSlugRoute: ServicesSlugRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  ConsultationRoute: ConsultationRoute,
  ContactRoute: ContactRoute,
  DeliveryRoute: DeliveryRoute,
  FaqRoute: FaqRoute,
  LoginRoute: LoginRoute,
  PlansRoute: PlansRoute,
  PortfolioRoute: PortfolioRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  ProductsRoute: ProductsRouteWithChildren,
  ServicesRoute: ServicesRouteWithChildren,
  SignupRoute: SignupRoute,
  TermsRoute: TermsRoute,
  VijuRoute: VijuRoute,
  VisualizeRoute: VisualizeRoute,
  ApiGenerateImageRoute: ApiGenerateImageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
